# Generated by Django 3.2.4 on 2021-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/olamigoke/image/upload/v1620480457/Wrent/profile_picture_jb3g6m.png'),
        ),
    ]
